[package]
name = "sound-test"
version = "0.1.0"
authors = ["John Asper <agentx1994@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.10"
lazy_static = "1.4"
sdl2 = "0.32"
